name: i2m
channels:
  - https://mirrors.ustc.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - rdkit
  - pandas
  - numpy
  - opencv
  - pillow
  - scipy
  - scikit-learn
  - scikit-image
  - matplotlib
  - tqdm
  - pyyaml
  - pip
  - pip:
    - paddleocr
    - paddlepaddle-gpu
    - SmilesPE
    - cairosvg
    - pycocotools