#!/bin/bash
# Script to guide users on downloading evaluation datasets

echo "=========================================="
echo "I2M Evaluation Data Setup Guide"
echo "=========================================="
echo ""
echo "Evaluation datasets are NOT included in this repository."
echo "You must download them separately."
echo ""
echo "Required location:"
echo "  /recovery/bo/pys/i2m_data/real/"
echo ""
echo "Available Datasets:"
echo "-------------------"
echo ""
echo "1. ACS (ACS journal molecular structures)"
echo "   Location: /recovery/bo/pys/i2m_data/real/acs/"
echo "   Files needed:"
echo "     - acs.csv"
echo "     - acs_ac/ (directory with ~660 images)"
echo ""
echo "2. JPO (Journal of Patent Office)"
echo "   Location: /recovery/bo/pys/i2m_data/real/JPO/"
echo "   Files needed:"
echo "     - JPO.csv"
echo "     - JPO_ac/ (directory with ~900 images)"
echo ""
echo "3. UOB (University of Birmingham)"
echo "   Location: /recovery/bo/pys/i2m_data/real/UOB/"
echo "   Files needed:"
echo "     - UOB.csv"
echo "     - UOB_ac/ (directory with ~11,480 images)"
echo ""
echo "4. USPTO (US Patent Office)"
echo "   Location: /recovery/bo/pys/i2m_data/real/USPTO/"
echo "   Files needed:"
echo "     - USPTO.csv"
echo "     - USPTO_ac/ (directory with ~11,440 images)"
echo ""
echo "5. CLEF (CLEF challenge)"
echo "   Location: /recovery/bo/pys/i2m_data/real/CLEF/"
echo "   Files needed:"
echo "     - CLEF.csv"
echo "     - CLEF_ac/ (directory with ~1,985 images)"
echo ""
echo "6. Staker (Staker benchmark)"
echo "   Location: /recovery/bo/pys/i2m_data/real/staker/"
echo "   Files needed:"
echo "     - staker.csv"
echo "     - staker_ac/ (directory with ~66,190 images)"
echo ""
echo "7. ChemVLOCR"
echo "   Location: /recovery/bo/pys/i2m_data/real/chemvlocr/"
echo "   Files needed:"
echo "     - chemvlocr.csv"
echo "     - chemvlocr_ac/ (directory with ~1,000 images)"
echo ""
echo "=========================================="
echo "Expected Directory Structure"
echo "=========================================="
echo ""
echo "/recovery/bo/pys/i2m_data/real/"
echo "│   ├── acs.csv"
echo "│   └── acs_ac/"
echo "│       ├── image1.png"
echo "│       ├── image2.png"
echo "│       └── ..."
echo "│   ├── JPO.csv"
echo "│   └── JPO_ac/"
echo "│   ├── UOB.csv"
echo "│   └── UOB_ac/"
echo "│   ├── USPTO.csv"
echo "│   └── USPTO_ac/"
echo "│   ├── CLEF.csv"
echo "│   └── CLEF_ac/"
echo "│   ├── staker.csv"
echo "│   └── staker_ac/"
echo "    ├── chemvlocr.csv"
echo "    └── chemvlocr_ac/"
echo "change names from xxx_ac to xxx"
echo "=========================================="
echo "After Downloading Data"
echo "========================================""
echo ""
echo "1. Verify data structure:"
echo "   ls /recovery/bo/pys/i2m_data/real/acs/"
echo ""
echo "2. Run evaluation:"
echo "   python evaluate/eval_model.py \\"
echo "       --weights weights/I2M_R4.onnx \\"
echo "       --dataset acs"
echo ""
echo "For more details, see: evaluate/README.md"
echo ""
echo "=========================================="
